version: "3"

services:

 web:
  container_name: web
  image: dockerfile
  restart: always
  build: .
  ports:
  - "8000:8000"
  links:
  - mongo
  depends_on: mongo

 mongo:
  container_name: mongo
  image: mongo
  volumes:
  - ./data:/data/db
  ports:
  - '27017:27017'
  command: mongod --quiet
